const CONFIG=window.KAIZEN_CONFIG||{}, BASE=window.KAIZEN_PRODUCTS||[];const $=s=>document.querySelector(s);let session=null,products=[],editing=null;
function status(el,msg,bad=false){el.textContent=msg;el.style.color=bad?'#ff6a82':'#8f949d'}
function headers(auth=true){const h={apikey:CONFIG.SUPABASE_ANON_KEY,'Content-Type':'application/json'};if(auth&&session?.access_token)h.Authorization=`Bearer ${session.access_token}`;else h.Authorization=`Bearer ${CONFIG.SUPABASE_ANON_KEY}`;return h}
function configured(){return !!(CONFIG.SUPABASE_URL&&CONFIG.SUPABASE_ANON_KEY)}
async function login(email,password){const r=await fetch(`${CONFIG.SUPABASE_URL}/auth/v1/token?grant_type=password`,{method:'POST',headers:{apikey:CONFIG.SUPABASE_ANON_KEY,'Content-Type':'application/json'},body:JSON.stringify({email,password})});if(!r.ok)throw new Error('Sign-in failed');return r.json()}
async function verifyAdmin(){const uid=session.user.id;const r=await fetch(`${CONFIG.SUPABASE_URL}/rest/v1/profiles?id=eq.${uid}&select=role`,{headers:headers()});if(!r.ok)throw new Error('Could not verify admin profile');const rows=await r.json();if(rows?.[0]?.role!=='admin')throw new Error('This account is not authorized as an admin.')}
async function loadProducts(){const r=await fetch(`${CONFIG.SUPABASE_URL}/rest/v1/${CONFIG.PRODUCT_TABLE||'products'}?select=*&order=sort_order.asc.nullslast,name.asc`,{headers:headers()});if(!r.ok)throw new Error('Could not load products');products=await r.json();renderList()}
function renderList(){$('#adminProducts').innerHTML=products.length?products.map(p=>`<div class="admin-product"><div class="admin-thumb">${p.image_url?`<img src="${p.image_url}" alt="">`:'K'}</div><div><strong>${p.name}</strong><small>${p.category} · $${p.price}</small></div><button data-edit="${p.slug}">Edit</button></div>`).join(''):'<div class="status">No database products yet. Import the base catalog.</div>';document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editProduct(products.find(p=>p.slug===b.dataset.edit)))}
function editProduct(p){editing=p||null;$('#productId').value=p?.id||'';$('#productName').value=p?.name||'';$('#productSlug').value=p?.slug||'';$('#productPrice').value=p?.price??'';$('#productCategory').value=p?.category||'Attraction';$('#productDescription').value=p?.description||'';$('#imageUrl').value=p?.image_url||'';$('#productActive').checked=p?.active!==false;preview(p?.image_url||'');window.scrollTo({top:0,behavior:'smooth'})}
function preview(url){$('#imagePreview').innerHTML=url?`<img src="${url}" alt="Product preview">`:'<span>No image</span>'}
async function uploadImage(file,slug){const ext=(file.name.split('.').pop()||'jpg').toLowerCase();const path=`${slug}.${ext}`;const r=await fetch(`${CONFIG.SUPABASE_URL}/storage/v1/object/${CONFIG.IMAGE_BUCKET||'product-images'}/${path}`,{method:'POST',headers:{apikey:CONFIG.SUPABASE_ANON_KEY,Authorization:`Bearer ${session.access_token}`,'Content-Type':file.type||'application/octet-stream','x-upsert':'true'},body:file});if(!r.ok)throw new Error('Image upload failed. Check Storage policies.');return `${CONFIG.SUPABASE_URL}/storage/v1/object/public/${CONFIG.IMAGE_BUCKET||'product-images'}/${path}?v=${Date.now()}`}
async function saveProduct(e){e.preventDefault();const s=$('#saveStatus');status(s,'Saving…');try{let image=$('#imageUrl').value.trim(),slug=$('#productSlug').value.trim().toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');const f=$('#imageFile').files[0];if(f)image=await uploadImage(f,slug);const payload={name:$('#productName').value.trim(),slug,price:Number($('#productPrice').value),category:$('#productCategory').value,description:$('#productDescription').value.trim(),image_url:image||null,active:$('#productActive').checked};const r=await fetch(`${CONFIG.SUPABASE_URL}/rest/v1/${CONFIG.PRODUCT_TABLE||'products'}?on_conflict=slug`,{method:'POST',headers:{...headers(),Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify(payload)});if(!r.ok)throw new Error(await r.text()||'Save failed');status(s,'Saved. The storefront will use the updated product data.');$('#imageUrl').value=image;preview(image);await loadProducts()}catch(err){status(s,err.message,true)}}
async function seedCatalog(){if(!confirm('Import the current Kaizen catalog into Supabase? Existing slugs will be updated.'))return;try{const rows=BASE.map((p,i)=>({...p,sort_order:i+1,active:true}));const r=await fetch(`${CONFIG.SUPABASE_URL}/rest/v1/${CONFIG.PRODUCT_TABLE||'products'}?on_conflict=slug`,{method:'POST',headers:{...headers(),Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(rows)});if(!r.ok)throw new Error(await r.text());await loadProducts()}catch(e){alert(e.message)}}
$('#loginForm').onsubmit=async e=>{e.preventDefault();if(!configured()){status($('#loginStatus'),'Add SUPABASE_URL and SUPABASE_ANON_KEY in config.js first.',true);return}status($('#loginStatus'),'Checking access…');try{session=await login($('#email').value,$('#password').value);await verifyAdmin();sessionStorage.setItem('kaizen_admin_session',JSON.stringify(session));$('#loginView').classList.add('hidden');$('#dashboard').classList.remove('hidden');$('#configNotice').textContent='Catalog images and product details are managed through Supabase. This page is intentionally not linked from the storefront.';await loadProducts()}catch(e){status($('#loginStatus'),e.message,true)}};
$('#productForm').onsubmit=saveProduct;$('#seedBtn').onclick=seedCatalog;$('#newBtn').onclick=()=>editProduct(null);$('#imageFile').onchange=e=>{const f=e.target.files[0];if(f)preview(URL.createObjectURL(f))};$('#imageUrl').oninput=e=>preview(e.target.value.trim());$('#logoutBtn').onclick=()=>{sessionStorage.removeItem('kaizen_admin_session');location.reload()};
(async()=>{try{const raw=sessionStorage.getItem('kaizen_admin_session');if(!raw||!configured())return;session=JSON.parse(raw);await verifyAdmin();$('#loginView').classList.add('hidden');$('#dashboard').classList.remove('hidden');$('#configNotice').textContent='Private catalog control is connected.';await loadProducts()}catch{sessionStorage.removeItem('kaizen_admin_session')}})();
