const CONFIG=window.KAIZEN_CONFIG||{};
const FALLBACK_PRODUCTS=(window.KAIZEN_PRODUCTS||[]).map((p,i)=>({...p,active:true,sort_order:i+1,image_url:"",description:""}));
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const routes=["home","explore","attraction","improvement","lifestyle","success","membership"];
const routeTheme={home:["207,210,216","#cfd2d8"],explore:["207,210,216","#cfd2d8"],attraction:["255,54,93","#ff365d"],improvement:["77,163,255","#4da3ff"],lifestyle:["156,99,255","#9c63ff"],success:["208,170,99","#d0aa63"],membership:["207,210,216","#cfd2d8"]};
const cardRGB={Attraction:"255,54,93",Improvement:"77,163,255",Lifestyle:"156,99,255",Success:"208,170,99"};
let PRODUCTS=[...FALLBACK_PRODUCTS],selected=null,activeFilter="all",cart=[];
const CART_KEY="kaizen_cart_v2";

function esc(v=""){return String(v).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[m]))}
function setRouteTheme(route){const t=routeTheme[route]||routeTheme.explore;document.documentElement.style.setProperty("--route-rgb",t[0]);document.documentElement.style.setProperty("--route",t[1])}
async function loadHeroContent(){if(!CONFIG.SUPABASE_URL||!CONFIG.SUPABASE_ANON_KEY)return;try{const r=await fetch(`${CONFIG.SUPABASE_URL}/rest/v1/homepage_content?select=value&key=eq.hero&limit=1`,{headers:{apikey:CONFIG.SUPABASE_ANON_KEY,Authorization:`Bearer ${CONFIG.SUPABASE_ANON_KEY}`}});if(!r.ok)return;const rows=await r.json(),h=rows?.[0]?.value;if(!h)return;const set=(s,v)=>{const el=$(s);if(el&&v)el.textContent=v};set("#heroEyebrow",h.eyebrow);set("#heroTitleLead",h.title_lead);set("#heroTitleAccent",h.title_accent);set("#heroDescription",h.description);set("#heroPrimaryCta",h.primary_cta_label);set("#heroSecondaryCta",h.secondary_cta_label)}catch(e){console.warn("Hero fallback active")}}
function initHeroMotion(){const hero=$(".hero"),visual=$(".hero-visual");if(!hero||!visual||matchMedia("(prefers-reduced-motion: reduce)").matches)return;hero.addEventListener("pointermove",e=>{if(e.pointerType==="touch")return;const r=hero.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;hero.style.setProperty("--hero-x",`${(x*12).toFixed(1)}px`);hero.style.setProperty("--hero-y",`${(y*9).toFixed(1)}px`)});hero.addEventListener("pointerleave",()=>{hero.style.setProperty("--hero-x","0px");hero.style.setProperty("--hero-y","0px")})}

async function loadRemoteCatalog(){if(!CONFIG.SUPABASE_URL||!CONFIG.SUPABASE_ANON_KEY)return;try{const r=await fetch(`${CONFIG.SUPABASE_URL}/rest/v1/${CONFIG.PRODUCT_TABLE||"products"}?select=*&active=eq.true&status=eq.published&kind=eq.subliminal&order=sort_order.asc.nullslast`,{headers:{apikey:CONFIG.SUPABASE_ANON_KEY,Authorization:`Bearer ${CONFIG.SUPABASE_ANON_KEY}`}});if(!r.ok)return;const remote=await r.json();if(!Array.isArray(remote)||!remote.length)return;PRODUCTS=remote.map(p=>({...p,name:p.name||p.title,price:Number(p.price??(Number(p.price_cents||0)/100)),category:p.category==="Self Improvement"?"Improvement":p.category,image_url:p.image_url||p.legacy_image_url||"",description:p.long_description||p.description||"",flagship:!!p.is_featured})).filter(p=>p.active!==false)}catch(e){console.warn("Catalog fallback active")}}
function route(){const r=(location.hash||"#home").slice(1).toLowerCase(),current=routes.includes(r)?r:"home";setRouteTheme(current);$$('.route').forEach(el=>el.classList.toggle('visible',el.dataset.route.split(' ').includes(current)));$$('.bottom-nav a').forEach(a=>a.classList.toggle('active',a.dataset.nav===current||(current!=="home"&&current!=="membership"&&a.dataset.nav==="explore")));if(["explore","attraction","improvement","lifestyle","success"].includes(current)){activeFilter=current==="explore"?"all":current[0].toUpperCase()+current.slice(1);updateFilterButtons();$('#catalogTitle').textContent=current==="explore"?"Explore Kaizen":activeFilter;render()}closeMenu();window.scrollTo({top:0,behavior:'smooth'})}
function updateFilterButtons(){$$('#filterRow button').forEach(b=>b.classList.toggle('active',b.dataset.filter===activeFilter))}
function render(){const q=($('#searchInput')?.value||'').trim().toLowerCase();const items=PRODUCTS.filter(p=>(activeFilter==='all'||p.category===activeFilter)&&(!q||p.name.toLowerCase().includes(q)));$('#productGrid').innerHTML=items.length?items.map(productMarkup).join(''):'<div class="empty">No matching subliminals.</div>';$$('.product-card').forEach(c=>c.addEventListener('click',()=>openProduct(c.dataset.slug)));observeReveals()}
function productMarkup(p){const rgb=cardRGB[p.category]||'207,210,216';const label=p.flagship?`FLAGSHIP • ${p.category}`:p.category;return `<article class="product-card reveal" data-slug="${esc(p.slug)}" style="--card-rgb:${rgb}"><div class="product-image">${p.image_url?`<img src="${esc(p.image_url)}" alt="${esc(p.name)}" loading="lazy">`:`<div class="fallback">K</div>`}</div><div class="product-content"><span class="tag">${esc(label)}</span><h3>${esc(p.name)}</h3><div class="card-foot"><strong>${esc(CONFIG.CURRENCY||'USD')} ${Number(p.price).toFixed(Number(p.price)%1?2:0)}</strong><span>VIEW →</span></div></div></article>`}
function openProduct(slug){selected=PRODUCTS.find(p=>p.slug===slug);if(!selected)return;setRouteTheme(selected.category.toLowerCase());$('#sheetCategory').textContent=selected.category.toUpperCase();$('#sheetName').textContent=selected.name;$('#sheetPrice').textContent=`${CONFIG.CURRENCY||'USD'} $${selected.price}`;$('#sheetDescription').textContent=selected.description||`${selected.name} is a focused Kaizen subliminal within the ${selected.category.toLowerCase()} collection, designed for consistent personal use and deliberate refinement.`;const art=$('#sheetArt');art.innerHTML=selected.image_url?`<img src="${esc(selected.image_url)}" alt="${esc(selected.name)}">`:'<div class="sheet-art-monogram">K</div>';$('#productSheet').classList.add('open');$('#productSheet').setAttribute('aria-hidden','false')}
function closeProduct(){$('#productSheet').classList.remove('open');$('#productSheet').setAttribute('aria-hidden','true');const r=(location.hash||'#home').slice(1);setRouteTheme(routeTheme[r]?r:'explore')}
function openMenu(){$('#menuShell').classList.add('open');$('#menuShell').setAttribute('aria-hidden','false')}
function closeMenu(){$('#menuShell').classList.remove('open');$('#menuShell').setAttribute('aria-hidden','true')}
function loadCart(){try{cart=JSON.parse(localStorage.getItem(CART_KEY)||'[]')}catch{cart=[]}renderCart()}
function saveCart(){localStorage.setItem(CART_KEY,JSON.stringify(cart));renderCart()}
function addToCart(p){if(!p)return;if(!cart.includes(p.slug))cart.push(p.slug);saveCart();openCart()}
function removeFromCart(slug){cart=cart.filter(x=>x!==slug);saveCart()}
function cartProducts(){return cart.map(s=>PRODUCTS.find(p=>p.slug===s)).filter(Boolean)}
function renderCart(){const items=cartProducts(),count=items.length,total=items.reduce((a,p)=>a+Number(p.price||0),0);$('#cartCount').textContent=count;$('#mobileCartCount').textContent=count;$('#cartTotal').textContent=`${CONFIG.CURRENCY||'USD'} $${total.toFixed(2)}`;$('#cartItems').innerHTML=items.length?items.map(p=>{const rgb=cardRGB[p.category]||'207,210,216';return `<div class="cart-item" style="--item-rgb:${rgb}"><div class="cart-thumb">${p.image_url?`<img src="${esc(p.image_url)}" alt="">`:'K'}</div><div><strong>${esc(p.name)}</strong><small>${CONFIG.CURRENCY||'USD'} $${p.price}</small></div><button class="remove" data-remove="${esc(p.slug)}" aria-label="Remove">×</button></div>`}).join(''):'<div class="cart-empty">Your cart is empty.<br><small>Choose a subliminal to begin.</small></div>';$$('[data-remove]').forEach(b=>b.onclick=()=>removeFromCart(b.dataset.remove));$('#checkoutBtn').disabled=!items.length}
function openCart(){renderCart();$('#cartShell').classList.add('open');$('#cartShell').setAttribute('aria-hidden','false')}
function closeCart(){$('#cartShell').classList.remove('open');$('#cartShell').setAttribute('aria-hidden','true');$('#paypalButtons').innerHTML='';$('#checkoutBtn').style.display='inline-flex'}
async function loadPayPal(){if(window.paypal)return true;if(!CONFIG.PAYPAL_CLIENT_ID)return false;return new Promise(resolve=>{const s=document.createElement('script');s.src=`https://www.paypal.com/sdk/js?client-id=${encodeURIComponent(CONFIG.PAYPAL_CLIENT_ID)}&currency=${CONFIG.CURRENCY||'USD'}`;s.onload=()=>resolve(!!window.paypal);s.onerror=()=>resolve(false);document.head.appendChild(s)})}
async function checkout(){const items=cartProducts();if(!items.length)return;const ready=await loadPayPal();if(!ready){alert('Checkout is temporarily unavailable.');return}$('#checkoutBtn').style.display='none';$('#paypalButtons').innerHTML='';const total=items.reduce((a,p)=>a+Number(p.price||0),0).toFixed(2);paypal.Buttons({style:{shape:'pill',layout:'vertical',label:'pay'},createOrder:(data,actions)=>actions.order.create({purchase_units:[{description:`Kaizen — ${items.map(p=>p.name).join(', ')}`.slice(0,127),amount:{currency_code:CONFIG.CURRENCY||'USD',value:total}}]}),onApprove:async(data,actions)=>{const details=await actions.order.capture();await recordOrder(data.orderID,details,items,total);cart=[];saveCart();$('#cartItems').innerHTML=`<div class="cart-empty"><strong style="color:#fff">Payment confirmed.</strong><br><small>Your Kaizen purchase has been received.</small></div>`;$('#paypalButtons').innerHTML='';$('#checkoutBtn').style.display='none'},onCancel:()=>{$('#checkoutBtn').style.display='inline-flex';$('#paypalButtons').innerHTML=''},onError:()=>{alert('PayPal could not complete checkout. Please try again.');$('#checkoutBtn').style.display='inline-flex';$('#paypalButtons').innerHTML=''}}).render('#paypalButtons')}
async function recordOrder(orderID,details,items,total){if(!CONFIG.SUPABASE_URL||!CONFIG.SUPABASE_ANON_KEY)return;const order={paypal_order_id:orderID,items:items.map(p=>p.slug),amount:Number(total),currency:CONFIG.CURRENCY||'USD',email:details?.payer?.email_address||'',status:'paid',created_at:new Date().toISOString()};try{await fetch(`${CONFIG.SUPABASE_URL}/rest/v1/orders`,{method:'POST',headers:{apikey:CONFIG.SUPABASE_ANON_KEY,Authorization:`Bearer ${CONFIG.SUPABASE_ANON_KEY}`,'Content-Type':'application/json',Prefer:'return=minimal'},body:JSON.stringify(order)})}catch{}}
function observeReveals(){const els=$$('.reveal:not(.in)');if(!('IntersectionObserver'in window)){els.forEach(e=>e.classList.add('in'));return}const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');io.unobserve(e.target)}}),{threshold:.08});els.forEach(e=>io.observe(e))}
$('#searchInput').addEventListener('input',render);$$('#filterRow button').forEach(b=>b.addEventListener('click',()=>{activeFilter=b.dataset.filter;updateFilterButtons();render()}));$$('[data-close-product]').forEach(x=>x.addEventListener('click',closeProduct));$('#menuBtn').onclick=openMenu;$('#closeMenu').onclick=closeMenu;$$('[data-close-menu]').forEach(x=>x.onclick=closeMenu);$('#cartBtn').onclick=openCart;$('#mobileCartBtn').onclick=openCart;$('#closeCart').onclick=closeCart;$$('[data-close-cart]').forEach(x=>x.onclick=closeCart);$('#addToCartBtn').onclick=()=>{addToCart(selected);closeProduct()};$('#buyNowBtn').onclick=()=>{if(selected&&!cart.includes(selected.slug))cart.push(selected.slug);saveCart();closeProduct();openCart()};$('#checkoutBtn').onclick=checkout;window.addEventListener('hashchange',route);
(async()=>{loadCart();await Promise.all([loadRemoteCatalog(),loadHeroContent()]);renderCart();route();observeReveals();initHeroMotion()})();
