window.KAIZEN_CONFIG = {
  PAYPAL_CLIENT_ID: "AYQrEh-1u1RZtiKZ-RXr4QiiCZdATBmd7RGlvZkUBNhCvoN8pL1s6iPZbZoD4U148Ipnamap48LeGm_U",
  CURRENCY: "USD",
  SUPABASE_URL: "https://qywjqnvyhufvfznksbjg.supabase.co",
  SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJIUzI1NiIsInJlZiI6InF5d2pxbnZ5aHVmdmZ6bmtzYmpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODI4NTU2OTgsImV4cCI6MjA5ODQzMTY5OH0.54JjZxEByKdba8lz5H8gS0lLcJ2r8XOUYeXNFbYDTBg",
  PRODUCT_TABLE: "products",
  IMAGE_BUCKET: "product-images",
  DOWNLOAD_BASE_URL: ""
};
