-- KAIZEN PRODUCTION CHECKOUT MIGRATION
-- Run this ONCE in Supabase SQL Editor after the base Kaizen setup.
-- This removes anonymous ability to mark orders paid and creates server-only
-- checkout/entitlement records for the Vercel PayPal functions.

-- Ensure the columns expected by the secure storefront exist.
alter table public.products add column if not exists description text not null default '';
alter table public.products add column if not exists image_url text;
alter table public.products add column if not exists active boolean not null default true;
alter table public.products add column if not exists sort_order integer;
alter table public.products add column if not exists updated_at timestamptz not null default now();

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  paypal_order_id text unique,
  items jsonb not null default '[]'::jsonb,
  amount numeric(10,2) not null default 0,
  currency text not null default 'USD',
  email text,
  status text not null default 'paid',
  created_at timestamptz not null default now()
);

create table if not exists public.paypal_checkouts (
  paypal_order_id text primary key,
  items jsonb not null default '[]'::jsonb,
  amount numeric(10,2) not null,
  currency text not null default 'USD',
  status text not null default 'created' check (status in ('created','paid','cancelled','failed')),
  payer_email text,
  capture_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.purchase_entitlements (
  id bigint generated by default as identity primary key,
  paypal_order_id text not null,
  product_slug text not null references public.products(slug) on delete restrict,
  user_id uuid references auth.users(id) on delete set null,
  email text,
  created_at timestamptz not null default now(),
  unique (paypal_order_id, product_slug)
);

alter table public.orders enable row level security;
alter table public.paypal_checkouts enable row level security;
alter table public.purchase_entitlements enable row level security;

-- IMPORTANT: remove the temporary browser-side order insert permission.
drop policy if exists "public order insert" on public.orders;

-- Do not create public insert/update policies for paypal_checkouts or
-- purchase_entitlements. The Vercel functions use the Supabase service-role key
-- server-side, which bypasses RLS safely.

-- Admins can inspect completed orders in a future/admin analytics screen.
drop policy if exists "admin orders read" on public.orders;
create policy "admin orders read"
on public.orders for select to authenticated
using (exists(select 1 from public.admin_users p where p.id=auth.uid() and p.role='admin'));

drop policy if exists "admin checkout read" on public.paypal_checkouts;
create policy "admin checkout read"
on public.paypal_checkouts for select to authenticated
using (exists(select 1 from public.admin_users p where p.id=auth.uid() and p.role='admin'));

drop policy if exists "admin entitlements read" on public.purchase_entitlements;
create policy "admin entitlements read"
on public.purchase_entitlements for select to authenticated
using (exists(select 1 from public.admin_users p where p.id=auth.uid() and p.role='admin'));

-- Recommended indexes for future dashboard/order lookup.
create index if not exists idx_orders_created_at on public.orders(created_at desc);
create index if not exists idx_orders_email on public.orders(email);
create index if not exists idx_entitlements_email on public.purchase_entitlements(email);
create index if not exists idx_entitlements_product on public.purchase_entitlements(product_slug);
