-- Kaizen temporary storefront database/admin setup
-- Run this in Supabase SQL Editor, then replace YOUR_ADMIN_EMAIL below.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'customer',
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  category text not null check (category in ('Attraction','Improvement','Lifestyle','Success')),
  price numeric(10,2) not null default 0,
  description text not null default '',
  image_url text,
  active boolean not null default true,
  sort_order integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  paypal_order_id text unique,
  items jsonb not null default '[]'::jsonb,
  amount numeric(10,2) not null default 0,
  currency text not null default 'USD',
  email text,
  status text not null default 'paid',
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;

-- A signed-in user may read their own profile so the admin UI can verify the role.
drop policy if exists "profile own read" on public.profiles;
create policy "profile own read" on public.profiles for select to authenticated using (id = auth.uid());

-- Public storefront may read visible products only.
drop policy if exists "public visible products" on public.products;
create policy "public visible products" on public.products for select to anon, authenticated using (active = true or exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));

-- Only admins may insert/update/delete products.
drop policy if exists "admin products insert" on public.products;
create policy "admin products insert" on public.products for insert to authenticated with check (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));
drop policy if exists "admin products update" on public.products;
create policy "admin products update" on public.products for update to authenticated using (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin')) with check (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));
drop policy if exists "admin products delete" on public.products;
create policy "admin products delete" on public.products for delete to authenticated using (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));

-- Temporary storefront order write. For the final store, move PayPal order creation/capture server-side.
drop policy if exists "public order insert" on public.orders;
create policy "public order insert" on public.orders for insert to anon, authenticated with check (true);

-- Public image bucket. Upload/delete is admin-only through Storage RLS.
insert into storage.buckets (id,name,public) values ('product-images','product-images',true) on conflict (id) do update set public=true;
drop policy if exists "admin product images insert" on storage.objects;
create policy "admin product images insert" on storage.objects for insert to authenticated with check (bucket_id='product-images' and exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));
drop policy if exists "admin product images update" on storage.objects;
create policy "admin product images update" on storage.objects for update to authenticated using (bucket_id='product-images' and exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin')) with check (bucket_id='product-images' and exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));

-- After creating your admin user in Supabase Auth, run this with your real email:
-- insert into public.profiles (id,role)
-- select id,'admin' from auth.users where email='YOUR_ADMIN_EMAIL'
-- on conflict (id) do update set role='admin';
